name: Golang

on:
  push:
    branches:
      - master

jobs:
  integration:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: setup
        uses: cedrickring/golang-action/go1.13@1.5.1

      - name: build
        run: go build

      - name: test
        run: go test
        env:
          GOKOA_ENV: test
